### ISSUE TITLE
Cannot read properties of undefined (reading 'replace')

### ISSUE THREAD

**Issue by liujianying** [Manx98/jsjiami-v6-decryptor#1]
脚本示例：curl 'https://bzjl.gitee.io/auto_hamibot_res/config/config_hamibot_bd_js_middle.js'
报错如下：
TypeError: Cannot read properties of undefined (reading 'replace')
    at _0x3f3328 (evalmachine.<anonymous>:1:447)
    at evalmachine.<anonymous>:1:602
    at evalmachine.<anonymous>:1:657
    at Script.runInContext (node:vm:141:12)
    at Object.runInContext (node:vm:297:6)
    at virtualGlobalEval (/Users/ljy/autjs/jsjiami-v6-decryptor-main/decryptor.js:291:15)
    at findStrEncryptionFunction (/Users/ljy/autjs/jsjiami-v6-decryptor-main/decryptor.js:311:9)
    at clearEncryptStrCode (/Users/ljy/autjs/jsjiami-v6-decryptor-main/decryptor.js:338:34)
    at decryptCode (/Users/ljy/autjs/jsjiami-v6-decryptor-main/decryptor.js:675:34)
    at Object.<anonymous> (/Users/ljy/autjs/jsjiami-v6-decryptor-main/decryptor.js:708:1)

**Comment by manx98** [comment]
我本地可以正常执行解密，有可能是依赖版本导致的，我固定了一下依赖库版本，请更新代码后重新 install 看看能否正常运行
```js
var config = {};
let app_config = {
    'script_env': 'hamibot',
    'import_moudles': [
        './common/common_utils',
        './common/download_install_utils',
        './common/video_utils',
        './bd/bd_common_executor',
        './bd/bd_js_executor'
    ],
    'script_open_moudles_flag': ['bd_js_open'],
    'script_moudles': ['bd_js_executor'],
    'is_init_ui': ![],
    'init_file': 'executor_new',
    'custom_config': {
        'bd_js_advertisement_extend': {
            'advertisement_extend': [
                'switch_open',
                'shopping',
                'live',
                'pdd',
                'follow',
                'open_page'
            ],
            'launch_app_name': '百度极速版',
            'launch_package_name': 'com.baidu.searchbox.lite'
        }
    }
};
config.getAllConfig = function () {
    return app_config;
};
module.exports = config;
_0xod2 = 'jsjiami.com.v6';
```
